### ISSUE TITLE
Which are the practical advantages over creating a normal store?

### ISSUE THREAD

**Issue by gplusdotgr** [jackmellis/mock-vuex#9]
First of all thank you for doing this - we definitely need something like arnaudbenard.com/redux-mock-store/ for Vue/Vuex. 

Question: What is the practical difference with using a normal Vuex store?

    store = new Vuex.Store({
      state,
      actions,
      getters,
    });

Speed & the helper methods I guess? But isn't re-creating your actions / mutations / state in tests a bit of an overhead - cheating? (I understand you're arguing that sometimes you wanna test pure component functionality without bothering with the store which is probably a legit argument but just to see if there's something else)

again thank you!

**Comment by jackmellis** [comment]
Yep mostly just the convenience to be honest. You can build up a mock store using your actual state object and then not have to worry about the actions/mutations. 

I’m a big fan of separation of concerns (and keeping components as dumb as possible) and it made sense to me to provide a lightweight mock alternative to vuex.

It also means in the future I can add more and more helper methods that wouldn’t ever be bundled with vuex to aid testing (and I’m certainly open to suggestions!)

**Comment by gplusdotgr** [comment]
the most BURNING thing for me would be async actions testing. In Redux mock,  http://arnaudbenard.com/redux-mock-store/ they have `store.getActions()`. 
I have to do a lot of manual effort to do the same thing now

**Comment by jackmellis** [comment]
If I’m understanding you right are we talking about asserting that specific actions/mutations have been triggered?

If so, this is what `store.expect` was meant for. Perhaps I misunderstand.

If you literally just want to get a list of all actions that have been triggered, that sounds like a fairly easy thing to add...

**Comment by gplusdotgr** [comment]
> If I’m understanding you right are we talking about asserting that specific actions/mutations have been triggered?

Yes.

But my use case is a bit more complex. Check : https://github.com/gkatsanos/voting/blob/master/src/store/__tests__/actions.spec.js#L48 (I have a commit/dispatch triggered as a callback/then() part of a Promise) , would store.expect catch that without me having to "await" and flushPromises?

**Comment by jackmellis** [comment]
If your action returned the `api.fetchItems` promise then you would just be able to do `await fetchItems({})` and it should consume all of the asynchronous actions in one go (rather than having to flush stuff) - in which case I think `expect` should in theory work. Something like:
```js
store.expect(‘receiveItems’)
await fetchItems({})
store.assert()
```
You get the idea

**Comment by gplusdotgr** [comment]
So , I assume that in order to test actions etc, I need to re-create a full-featured store: https://jackmellis.gitbooks.io/vuenit/content/store/full-featured.html . 
The problem there is I feel we're creating multiple "sources of truth" - who keeps the real store and the mock store synced as the application develops?

**Comment by jackmellis** [comment]
This is true, and something that has increased maintenance of some of my projects in the past. However, it's important to keep in mind that you *can* share stuff between your store and tests when testing.
```js
import { initialState, actions } from '../store';

const store = mockStore({
  state: initialState,
  actions: {
    actionUnderTest: actions.actionUnderTest,
  },
});
```
Using the *real* state object means you don't have to worry about that. And if you try to keep your tests isolated to just one action at a time, you shouldn't **need** to create a full store with every action and mutation mocked every single time, just pick and choose the bit's you're concerned with. 

One of the features of mock-vuex is that it automatically stubs all commits/actions that haven't been explicitly provided. If you are testing a component that fires off all sorts of actions/mutations, the mock store won't throw, it will just consume and resolve them as if they existed. Then you can add behaviour for the actions as and when you need to.
